# Generated by Django 2.2.1 on 2019-07-12 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_post_image_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_list',
        ),
    ]
