# Generated by Django 2.2.1 on 2019-07-13 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_remove_post_image_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_list',
            field=models.TextField(null=True),
        ),
    ]
