# Generated by Django 2.2.1 on 2019-07-13 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_post_image_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_list',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
