# Generated by Django 2.2.1 on 2019-07-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_post_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_list',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
