# Generated by Django 2.2.1 on 2019-07-14 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_auto_20190714_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
