# Generated by Django 2.2.1 on 2019-07-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_post_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='github',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
